spring:
  application:
    name: demotest

  datasource:
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: MYSQL
      show-sql: true
      use_sql_comments: true
      format_sql: true


server:
  port: 9019

